name: Direktiv Publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: go setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
      id: go
    - name: install ko
      working-directory: ./
      run: |
        curl -L https://github.com/google/ko/releases/download/v0.6.0/ko_0.6.0_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko
        sudo mv ko /usr/local/bin
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: build
      run: |
        mkdir -p /tmp/yamls/
        export KO_DOCKER_REPO='docker.io/vorteil'
        export KO_FLAGS="--platform=linux/amd64"
        export YAML_OUTPUT_DIR=/tmp/yamls
        ls -la
        hack/generate-yamls.sh . /tmp/files
    - name: upload
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GCP_BUCKET }}
        path: /tmp/files
        destination: direktiv_knative/
