name: Direktiv Publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: go setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
      id: go
    - name: install ko
      working-directory: ./
      run: |
        curl -L https://github.com/google/ko/releases/download/v0.6.0/ko_0.6.0_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko
        sudo mv ko /usr/local/bin
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      name: gcloud login
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_AUTH }}
# - name: Docker auth
#   run: |
#     gcloud auth configure-docker
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check out code
      uses: actions/checkout@v2
    - name: build
      run: |
        mkdir -p /tmp/yamls/
# export KO_DOCKER_REPO='gcr.io/direktiv'
        export KO_DOCKER_REPO='public.ecr.aws/w8c5d3s4/direktiv'
        export KO_FLAGS="--platform=linux/amd64"
        export YAML_OUTPUT_DIR=/tmp/yamls
        hack/generate-yamls.sh . /tmp/files
    # - name: upload
    #   uses: google-github-actions/upload-cloud-storage@main
    #   with:
    #     credentials: ${{ secrets.GCP_BUCKET }}
    #     path: /tmp/yamls
    #     destination: direktiv_knative/
    # - name: upload contour
    #   uses: google-github-actions/upload-cloud-storage@main
    #   with:
    #     credentials: ${{ secrets.GCP_BUCKET }}
    #     path: third_party/contour-latest/contour.yaml
    #     destination: direktiv_knative/yamls
    # - name: upload contour
    #   uses: google-github-actions/upload-cloud-storage@main
    #   with:
    #     credentials: ${{ secrets.GCP_BUCKET }}
    #     path: third_party/contour-latest/net-contour.yaml
    #     destination: direktiv_knative/yamls
