name: Direktiv Publish
on:
  workflow_dispatch:
  create:
    tags:
      - v*
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Check out code
      uses: actions/checkout@v2
    - name:
      run: |
        export KO_DOCKER_REPO='docker.io/vorteil'
        export KO_FLAGS="--platform=linux/amd64"
        export YAML_OUTPUT_DIR=/tmp/yamls
        ls -la
        hack/generate-yamls.sh . /tmp/files
